
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./www
    ports:
      - "8080:80"
  backend:
    build:
      dockerfile: Dockerfile
      context: ./api
    ports:
      - "3001:3001"

